### ISSUE TITLE
Rollback the Travis $TEST_SUITE changes

### ISSUE THREAD

**Issue by johnnyshields** [fatfreecrm/fat_free_crm#669]
@CloCkWeRX its making tests take a very long time.
 
Let's also only require Ruby 2.4 to pass.

**Comment by CloCkWeRX** [comment]
The builds slowed down with the initial changes to run with two rubies, and the swap from 'exclude' (don't build) to allowable failures (do build) in 1426f1547f957d0387ee282eaf2438ee7cb115a9

<img width="1680" alt="screen shot 2018-01-07 at 12 06 40 pm" src="https://user-images.githubusercontent.com/365751/34645650-4556751e-f3a3-11e7-844b-aee898731b5e.png">

The changes to run only certain things actually drop the execution a lot:
https://travis-ci.org/fatfreecrm/fat_free_crm/builds/325700650

The problem is travis seems to be rate limiting things - https://travis-ci.org/fatfreecrm/fat_free_crm/builds/325927926 had about 17 minutes or so of actual run time, but travis spread it out over an hour.

I'd be happy to go back to only building on one ruby and one target DB; but I'd like to keep more of the jobs split up - the feature tests are frequently the most flakey bits, so keeping them seperate means we can just use the "restart job" controls on the individual failed bit.

<img width="1342" alt="screen shot 2018-01-07 at 12 13 16 pm" src="https://user-images.githubusercontent.com/365751/34645693-3400e122-f3a4-11e7-9c3b-5d2c4d9e53b1.png">

That means when we are dealing with flakey tests, its a 2-5 minute rebuild instead of an entire test run.

**Comment by johnnyshields** [comment]
This is ok for now.
